# Generated by Django 4.1.5 on 2023-03-24 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("treatment_histories", "0002_create_image_for_analyzes_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentHistoryImageForAnalyzes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_for_analyzes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="treatment_histories.imageforanalyzes",
                    ),
                ),
                (
                    "treatment_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="treatment_histories.treatmenthistory",
                    ),
                ),
            ],
            options={
                "db_table": "treatment_history_image_for_analyzes",
            },
        ),
    ]
