# Generated by Django 4.1.5 on 2023-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "treatment_histories",
            "0004_relate_name_treatment_history_image_for_analyzes",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="imageforanalyzes",
            name="slug",
            field=models.SlugField(default="default", max_length=1000, unique=True),
            preserve_default=False,
        ),
    ]
