# Generated by Django 4.1.5 on 2023-04-20 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("treatment_histories", "0005_imageforanalyzes_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatmenthistoryimageforanalyzes",
            name="image_for_analyzes",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treatment_history_image_for_analyzes",
                related_query_name="treatment_history_image_for_analyzes",
                to="treatment_histories.imageforanalyzes",
            ),
        ),
        migrations.AlterField(
            model_name="treatmenthistoryimageforanalyzes",
            name="treatment_history",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treatment_history_image_for_analyzes",
                related_query_name="treatment_history_image_for_analyzes",
                to="treatment_histories.treatmenthistory",
            ),
        ),
    ]
