# Generated by Django 4.1.5 on 2023-04-21 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0004_documenttype_unicode_name"),
        (
            "treatment_histories",
            "0006_alter_treatmenthistoryimageforanalyzes_image_for_analyzes_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentHistoryDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document.document",
                    ),
                ),
                (
                    "treatment_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="treatment_histories.treatmenthistory",
                    ),
                ),
            ],
            options={
                "db_table": "treatment_history_document",
            },
        ),
    ]
