# Generated by Django 4.1.5 on 2023-04-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0004_documenttype_unicode_name"),
        ("treatment_histories", "0007_treatmenthistorydocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatmenthistorydocument",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treatment_history_document",
                related_query_name="treatment_history_document",
                to="document.document",
            ),
        ),
        migrations.AlterField(
            model_name="treatmenthistorydocument",
            name="treatment_history",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treatment_history_document",
                related_query_name="treatment_history_document",
                to="treatment_histories.treatmenthistory",
            ),
        ),
    ]
