# Generated by Django 4.1.5 on 2023-04-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("physical", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="physicalparameters",
            name="slug",
            field=models.SlugField(default="default", max_length=100),
            preserve_default=False,
        ),
    ]
