# Generated by Django 4.1.5 on 2023-04-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("physical", "0002_physicalparameters_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="physicalparameters",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
