# Generated by Django 4.1.5 on 2023-05-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("physical", "0003_physicalparameters_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="physicalparameters",
            options={
                "verbose_name": "Физический параметр",
                "verbose_name_plural": "Физические параметры",
            },
        ),
    ]
