version: '3.9'
services:
  front:
    restart: always
    build:
      context: .
      dockerfile: ./mssfront/Dockerfile
    container_name: vue-front
    ports:
      - 8000:8080
    depends_on:
      - backend
  backend:
    restart: always
    container_name: django-back
    build:
      context: .
      dockerfile: ./MSSProject/Dockerfile
    environment:
      - HOST=postgres_db
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB:?err}
      - POSTGRES_USER=${USER:?err}
      - POSTGRES_PASSWORD=${PASSWORD:?err}
    container_name: postgres_db
