# Generated by Django 4.1.5 on 2023-05-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_create_user_personal_info"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Роль", "verbose_name_plural": "Роли"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="userlocation",
            options={
                "verbose_name": "Локация пользователя",
                "verbose_name_plural": "Локация пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="userpersonalinfo",
            options={
                "verbose_name": "Персональная информация пользователя",
                "verbose_name_plural": "Персональная информация пользователей",
            },
        ),
    ]
