# Generated by Django 4.1.5 on 2023-04-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_change_user_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpersonalinfo",
            name="image",
        ),
    ]
