# Generated by Django 4.1.5 on 2023-05-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_create_appointments_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointments",
            options={
                "verbose_name": "Запись к врачу",
                "verbose_name_plural": "Записи к врачам",
            },
        ),
    ]
