# Generated by Django 4.1.5 on 2023-03-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("TEST", "Test"),
                            ("ANALYZES", "Analyzes"),
                            ("CONCLUSIONS", "Conclusions"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "db_table": "document_type",
            },
        ),
    ]
