# Generated by Django 4.1.5 on 2023-04-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0002_create_document_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
