# Generated by Django 4.1.5 on 2023-04-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0003_alter_document_name_alter_documenttype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttype",
            name="unicode_name",
            field=models.CharField(default="default", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
