# Generated by Django 4.1.5 on 2023-04-22 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import document.models.file_document


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctor", "0004_create_doctor_doctor_specialization_model"),
        ("document", "0004_documenttype_unicode_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200)),
                ("name", models.CharField(max_length=300)),
                (
                    "document",
                    models.FileField(
                        upload_to=document.models.file_document.media_path_builder_for_documents
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="doctor.doctor",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="document.documenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "file_document",
            },
        ),
    ]
