# Generated by Django 4.1.5 on 2023-05-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0005_filedocument"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "Документ", "verbose_name_plural": "Документы"},
        ),
        migrations.AlterModelOptions(
            name="documenttype",
            options={
                "verbose_name": "Тип документа",
                "verbose_name_plural": "Типы документа",
            },
        ),
    ]
