# Generated by Django 4.1.5 on 2023-03-23 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_create_doctor_specialization_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_summary", models.TextField()),
                ("summary", models.TextField()),
                (
                    "doctor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="doctor.doctor"
                    ),
                ),
            ],
            options={
                "db_table": "doctor_summary",
            },
        ),
    ]
