# Generated by Django 4.1.5 on 2023-03-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_create_doctor_summary_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorDoctorSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_doctor_specialization",
                        to="doctor.doctor",
                    ),
                ),
                (
                    "doctor_specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_doctor_specialization",
                        to="doctor.doctorspecialization",
                    ),
                ),
            ],
            options={
                "db_table": "doctor_doctor_specialization",
            },
        ),
    ]
