# Generated by Django 4.1.5 on 2023-05-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0004_create_doctor_doctor_specialization_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={"verbose_name": "Доктор", "verbose_name_plural": "Доктора"},
        ),
    ]
