# Generated by Django 4.1.5 on 2023-05-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0005_alter_doctor_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctordoctorspecialization",
            options={
                "verbose_name": "Специализация доктора - Доктор",
                "verbose_name_plural": "Специализации докторов - Доктора",
            },
        ),
        migrations.AlterModelOptions(
            name="doctorspecialization",
            options={
                "verbose_name": "Специализация доктора",
                "verbose_name_plural": "Специализации докторов",
            },
        ),
        migrations.AlterModelOptions(
            name="doctorsummary",
            options={
                "verbose_name": "Резюме Доктора",
                "verbose_name_plural": "Резюме Докторов",
            },
        ),
    ]
