# Generated by Django 4.1.3 on 2022-12-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="role name"
                    ),
                ),
            ],
            options={
                "db_table": "role",
            },
        ),
    ]
