# Generated by Django 4.1.3 on 2022-12-23 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userApp.models.user_personal_info


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0001_create_role_and_user_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=userApp.models.user_personal_info.media_path_builder_for_user_info,
                        verbose_name="user image",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="first name"),
                ),
                (
                    "second_name",
                    models.CharField(max_length=100, verbose_name="second name"),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="patronymic"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=100, verbose_name="email"),
                ),
                (
                    "gender",
                    models.CharField(blank=True, default="Other", max_length=150),
                ),
                ("age", models.IntegerField(blank=True, default=-1)),
                ("health_status", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_personal_info",
            },
        ),
    ]
