# Generated by Django 4.1.3 on 2022-11-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpersonalinfo",
            name="patronymic",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="patronymic"
            ),
        ),
    ]
