# Generated by Django 4.1.3 on 2022-11-28 14:33

from django.db import migrations, models
import userApp.models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0002_remove_doctor_doctor_type_doctor_doctor_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageforanalyzes",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=userApp.models.content_product_file_path,
                verbose_name="user image",
            ),
        ),
        migrations.AlterField(
            model_name="userpersonalinfo",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=userApp.models.content_product_file_path,
                verbose_name="user image",
            ),
        ),
    ]
