# Generated by Django 4.1.3 on 2022-12-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0003_create_user_location_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "document_type",
            },
        ),
    ]
