# Generated by Django 4.1.3 on 2022-11-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0003_doctors_doctortypes_imageforanalyzes_patients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctortypes",
            name="doctor_type",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="doctor profession name"
            ),
        ),
    ]
