# Generated by Django 4.1.3 on 2022-11-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0003_alter_imageforanalyzes_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="doctor_type",
        ),
        migrations.RemoveField(
            model_name="treatmenthistory",
            name="image",
        ),
        migrations.CreateModel(
            name="TreatmentHistoryImageForAnalyzes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_for_analyzes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userApp.imageforanalyzes",
                    ),
                ),
                (
                    "treatment_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userApp.treatmenthistory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorDoctorTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="userApp.doctor"
                    ),
                ),
                (
                    "doctor_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userApp.doctortype",
                    ),
                ),
            ],
        ),
    ]
