# Generated by Django 4.1.3 on 2022-11-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0004_alter_doctortypes_doctor_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctors",
            old_name="doctor_type_id",
            new_name="doctor_type",
        ),
        migrations.RenameField(
            model_name="doctors",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="patients",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="treatmentshistory",
            old_name="doctor_id",
            new_name="doctor",
        ),
        migrations.RenameField(
            model_name="treatmentshistory",
            old_name="user_id",
            new_name="user",
        ),
    ]
