# Generated by Django 4.1.3 on 2022-11-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0004_remove_doctor_doctor_type_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Roles",
            new_name="Role",
        ),
    ]
