# Generated by Django 4.1.3 on 2022-12-01 10:31

from django.db import migrations, models
import userApp.models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0005_rename_roles_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctortype",
            name="slug",
            field=models.SlugField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="slug",
            field=models.SlugField(default="default", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="treatmenthistory",
            name="slug",
            field=models.SlugField(default="default"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(default="default", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="imageforanalyzes",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=userApp.models.media_path_builder_for_analyzes_images,
                verbose_name="image for analyzes",
            ),
        ),
        migrations.AlterModelTable(
            name="doctor",
            table="doctor",
        ),
        migrations.AlterModelTable(
            name="doctordoctortypes",
            table="doctor_doctor_type",
        ),
        migrations.AlterModelTable(
            name="doctortype",
            table="doctor_type",
        ),
        migrations.AlterModelTable(
            name="imageforanalyzes",
            table="image_for_analyzes",
        ),
        migrations.AlterModelTable(
            name="role",
            table="role",
        ),
        migrations.AlterModelTable(
            name="treatmenthistory",
            table="treatment_history",
        ),
        migrations.AlterModelTable(
            name="treatmenthistoryimageforanalyzes",
            table="treatment_history_image_for_analyzes",
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
        migrations.AlterModelTable(
            name="userdocument",
            table="user_document",
        ),
        migrations.AlterModelTable(
            name="userpersonalinfo",
            table="user_personal_info",
        ),
    ]
