# Generated by Django 4.1.3 on 2022-11-27 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0005_rename_doctor_type_id_doctors_doctor_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentshistory",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="userApp.imageforanalyzes",
            ),
        ),
    ]
