# Generated by Django 4.1.3 on 2022-11-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0006_treatmentshistory_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Doctors",
            new_name="Doctor",
        ),
        migrations.RenameModel(
            old_name="Patients",
            new_name="Patient",
        ),
    ]
