# Generated by Django 4.1.3 on 2022-12-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0007_alter_user_managers_user_date_joined_user_email_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="patient",
            table="patient",
        ),
    ]
