# Generated by Django 4.1.3 on 2022-12-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0008_alter_patient_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpersonalinfo",
            name="email",
            field=models.EmailField(blank=True, max_length=100, verbose_name="email"),
        ),
    ]
