# Generated by Django 4.1.3 on 2022-11-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0008_remove_treatmentshistory_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="login",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="user login"
            ),
        ),
    ]
