# Generated by Django 4.1.3 on 2022-12-23 15:40

from django.db import migrations, models
import userApp.models.image_for_analyzes


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0009_create_patient_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageForAnalyzes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=userApp.models.image_for_analyzes.media_path_builder_for_analyzes_images,
                        verbose_name="image for analyzes",
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "image_for_analyzes",
            },
        ),
    ]
