# Generated by Django 4.1.3 on 2022-12-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0009_alter_userpersonalinfo_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdocument",
            name="slug",
            field=models.SlugField(default="default slug", max_length=100),
            preserve_default=False,
        ),
    ]
