# Generated by Django 4.1.3 on 2022-12-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0010_userdocument_slug"),
        ("userApp", "0011_userdocumenttype_slug"),
    ]

    operations = []
