# Generated by Django 4.1.3 on 2022-12-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0012_merge_20221215_1440"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctortype",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="treatmenthistory",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="userdocument",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="userdocumenttype",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name="userdocumenttype",
            table="user_document_type",
        ),
    ]
