# Generated by Django 4.1.3 on 2022-12-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0013_create_treatment_history_union_image_for_analyzes_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_summary", models.TextField()),
                ("summary", models.TextField()),
                (
                    "doctor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="userApp.doctor"
                    ),
                ),
            ],
            options={
                "db_table": "doctor_summary",
            },
        ),
    ]
