# Generated by Django 4.1.3 on 2022-12-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0013_alter_doctortype_slug_alter_role_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdocument",
            name="name",
            field=models.CharField(default="default name", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userdocument",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
