# Generated by Django 4.1.3 on 2022-12-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0013_create_document_creator_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentHistoryImageForAnalyzes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_for_analyzes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userApp.imageforanalyzes",
                    ),
                ),
                (
                    "treatment_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userApp.treatmenthistory",
                    ),
                ),
            ],
            options={
                "db_table": "treatment_history_image_for_analyzes",
            },
        ),
    ]
