# Generated by Django 4.1.5 on 2023-03-06 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0015_create_appointment_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmenthistory",
            name="conclusion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="treatmenthistory",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="treatmenthistory",
            name="short_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="treatmenthistory",
            name="title",
            field=models.TextField(blank=True),
        ),
    ]
