# Generated by Django 4.1.3 on 2022-12-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0015_userlocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpersonalinfo",
            name="age",
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name="userpersonalinfo",
            name="gender",
            field=models.CharField(blank=True, default="Other", max_length=150),
        ),
        migrations.AddField(
            model_name="userpersonalinfo",
            name="health_status",
            field=models.TextField(blank=True, default=""),
        ),
    ]
