# Generated by Django 4.1.3 on 2022-12-21 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0017_alter_userlocation_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDocumentDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="userApp.doctor",
                    ),
                ),
                (
                    "user_document",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="userApp.userdocument",
                    ),
                ),
            ],
            options={
                "db_table": "user_document_doctor",
            },
        ),
    ]
