# Generated by Django 4.1.5 on 2023-03-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0017_make_roles_form_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttype",
            name="name",
            field=models.CharField(
                choices=[
                    ("TEST", "Test"),
                    ("ANALYZES", "Analyzes"),
                    ("CONCLUSIONS", "Conclusions"),
                ],
                max_length=255,
            ),
        ),
    ]
