# Generated by Django 4.1.3 on 2022-12-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0019_imageforanalyzes_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctordoctortypes",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_doctor_types",
                to="userApp.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="doctordoctortypes",
            name="doctor_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_doctor_types",
                to="userApp.doctortype",
            ),
        ),
    ]
